# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19c6313be13b5165b505f34d64bc9796"
application_url = "https://serial-cuba-frost-exists.trycloudflare.com"
embedded = true
name = "tuanpa20-application"
handle = "tuanpa20-application"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tuanpa20-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = 

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://serial-cuba-frost-exists.trycloudflare.com/auth/callback",
  "https://serial-cuba-frost-exists.trycloudflare.com/auth/shopify/callback",
  "https://serial-cuba-frost-exists.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
