# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "438fd9150e97040c3fa3389056345fd8"
application_url = "https://rehab-kit-latina-houston.trycloudflare.com"
embedded = true
name = "tuanpa20-store"
handle = "tuanpa20-store"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rehab-kit-latina-houston.trycloudflare.com/auth/callback",
  "https://rehab-kit-latina-houston.trycloudflare.com/auth/shopify/callback",
  "https://rehab-kit-latina-houston.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "tuanpa20-store.myshopify.com"
automatically_update_urls_on_dev = true
